### ISSUE TITLE
[Question] Purpose of the project.

### ISSUE THREAD

**Issue by enricoangelon** [NetherGamesMC/ProxyTransport-PM#89]
Hi, what would the point of having a similar proxy be? In the proxy you declare the following "Proxy Transport is a TCP transport protocol implementation to replace the inefficient RakNet protocol implementation between proxies and downstream servers", it is now obvious to ask yourself "If you declare that RakNet is inefficient, does it make sense to use the same raknet as the basis to communicate with the game and then also the TCP?". In short, you are simply adding an overhead without any sense, but even if it were, RakNet can be very efficient (as demonstrated with MiNET). Still, it must be implemented with a low-level language (or at least one that allows you to at least control the memory) to achieve this objective. Would it perhaps make more sense to modify raknet by adding a new header instead of 0xFE (BATCH), but perhaps 0xF3 (PROXY) and have a proxy and a server communicate via this packet with custom packets? As a result, the waste of open resources would be avoided and perhaps it would be more efficient.

**Comment by SenseiTarzan** [comment]
Proxy transporter is there to reduce network costs thanks to compression with zstd but also to avoid packet losses which can come from the UDP protocol, remember that it is bothers because when a chunk and persu the player has a display bug and it helps to alleviate this kind of problem afterwards I understand your question but the problem is that you put back in question the proxy and not the plugin that I suggest you go directly to the WaterdogPE GitHub which offers the proxy solution

**Comment by SenseiTarzan** [comment]
Proxy carrier is there to reduce network costs thanks to compression with zstd but also to avoid packet losses that can come from the UDP protocol, remember that it is annoying because when a chunk is lost, players have a bug  display and it helps to alleviate this kind of problem afterwards I understand your question but the problem is that you are questioning the proxy and not the plugin that I suggest you go directly to the WaterdogPE GitHub which offers the  solution
